<a href="https://colab.research.google.com/github/Mikkk1/Intro-to-Linear-Algebra-python/blob/main/linearAlg_seg_1_topic_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Matrices** (Rank 2 Tensors)
* 2D array of numbers.
* Denoted by Uppercse itallics, bold, e.g. ***X***
* Represented as:
  * ***X*** = (n<sub>row</sub>, n<sub>col</sub>)
  * ***X*** has 3 rows and 2 columns, if its shape is (3, 2).
* Individual scaler element is denoted by uppercase, itallics only. e.g.,
  * So, the element on the top right corner of the matrix ***X*** would be *X*<sub>1,2</sub>
* Colon reppresents the entire row or column.
  * Left column of matrix ***X*** is ***X***<sub>:,1</sub>

## In Numpy:

In [3]:
import numpy as np
import tensorflow as tf

In [4]:
# use array() with nested brackets:

X = np.array([[25, 2],[5, 6], [7, 10]])
X

array([[25,  2],
       [ 5,  6],
       [ 7, 10]])

In [7]:
X.shape

(3, 2)

In [6]:
X.size

6

Left column of matrix: (Starts from 0 Index in programming, from 1 in Maths)

In [8]:
X[:,0]

array([25,  5,  7])

In [9]:
X[2,:]

array([ 7, 10])

In [10]:
X[0:2]

array([[25,  2],
       [ 5,  6]])

## In TensorFlow

In [13]:
X_tf = tf.Variable([[25, 2],[5, 6], [7, 10]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5,  6],
       [ 7, 10]], dtype=int32)>

In [14]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [15]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [17]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>

# Generic Tensor Notation
## Higher-Rank tensors:
* Denoted by Uppercase, bold, itallics
* In a 4-Tensor ***X*** (4D tensor), element at position *(i, j, k, l)* will be denoted as ***X***<sub>*(i,j,k,l)*</sub>
* As an example, Rank 4 Tensors are common for images, where each dimension refers to:
  1.   Number of images in training batch, e.g. 32
  2.   Image height in pixels, e.g. 28
  3.   Image width in pixels, e.g. 28
  4.   Number of color channels, e.g. 3 for full color images (RGB)
  



In [18]:
# In real models, we replace images with the zeros.
images_tf = tf.zeros([32, 28, 28, 3])

In [ ]:
images_tf

Segment 1 ends here.