<a href="https://colab.research.google.com/github/Mikkk1/Intro-to-Linear-Algebra-python/blob/main/linearAlg_seg_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensor Transposition:**

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
X = np.array([[25, 3, 9], [7, 10, 11], [12, 63, 2]])

In [ ]:
X

array([[25,  3,  9],
       [ 7, 10, 11],
       [12, 63,  2]])

In [ ]:
X.T

array([[25,  7, 12],
       [ 3, 10, 63],
       [ 9, 11,  2]])

In [ ]:
X_tf = tf.Variable([[25, 3, 9], [7, 10, 11], [12, 63, 2]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[25,  3,  9],
       [ 7, 10, 11],
       [12, 63,  2]], dtype=int32)>

In [ ]:
tf.transpose(X_tf)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[25,  7, 12],
       [ 3, 10, 63],
       [ 9, 11,  2]], dtype=int32)>

# Basic Tensor Arithmatic:

Adding and multiplying with scalers:

In [ ]:
X + 2

array([[27,  5, 11],
       [ 9, 12, 13],
       [14, 65,  4]])

In [ ]:
X * 2

array([[ 50,   6,  18],
       [ 14,  20,  22],
       [ 24, 126,   4]])

In [ ]:
X * 2 + 2

array([[ 52,   8,  20],
       [ 16,  22,  24],
       [ 26, 128,   6]])

In [ ]:
X_tf * 2 + 2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 52,   8,  20],
       [ 16,  22,  24],
       [ 26, 128,   6]], dtype=int32)>

In [ ]:
tf.add(tf.multiply(X_tf, 2),2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 52,   8,  20],
       [ 16,  22,  24],
       [ 26, 128,   6]], dtype=int32)>

### The Hadamard Product (The element-wise product):


#### In Numpy

In [ ]:
X

array([[25,  3,  9],
       [ 7, 10, 11],
       [12, 63,  2]])

In [ ]:
A = X + 2

In [ ]:
A

array([[27,  5, 11],
       [ 9, 12, 13],
       [14, 65,  4]])

In [ ]:
A + X

array([[ 52,   8,  20],
       [ 16,  22,  24],
       [ 26, 128,   6]])

In [ ]:
A * X

array([[ 675,   15,   99],
       [  63,  120,  143],
       [ 168, 4095,    8]])

#### In Tensorflow

In [ ]:
A_tf = X_tf + 2

In [ ]:
A_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[27,  5, 11],
       [ 9, 12, 13],
       [14, 65,  4]], dtype=int32)>

In [ ]:
A_tf + X_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 52,   8,  20],
       [ 16,  22,  24],
       [ 26, 128,   6]], dtype=int32)>

In [ ]:
A_tf * X_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 675,   15,   99],
       [  63,  120,  143],
       [ 168, 4095,    8]], dtype=int32)>

### Reduction:
Calculating sum accross all the elements of a tensor, e.g.
* For vector ***x*** of length n, we calculate: $\sum_{i=1}^{n} x_i$
* For matrix ***X*** with m by n dimension, we calculate $\sum_{i=1}^{m} \sum_{i=1}^{n} X_{i,j}$

## Sum:

In [ ]:
X

array([[25,  3,  9],
       [ 7, 10, 11],
       [12, 63,  2]])

In [ ]:
X.sum()

142

In [ ]:
X_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[25,  3,  9],
       [ 7, 10, 11],
       [12, 63,  2]], dtype=int32)>

In [ ]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=142>

Sum of only rows:

In [ ]:
X.sum(axis = 0)

array([44, 76, 22])

In [ ]:
tf.reduce_sum(X_tf, 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([44, 76, 22], dtype=int32)>

Sum of only columns:

In [ ]:
X.sum(axis = 1)

array([37, 28, 77])

In [ ]:
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([37, 28, 77], dtype=int32)>

## Max:

In [ ]:
X.max()

63

In [ ]:
tf.math.reduce_max(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=63>

## Min:

In [ ]:
X.min()

2

In [ ]:
tf.math.reduce_min(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Mean

In [ ]:
X.mean()

15.777777777777779

In [ ]:
tf.math.reduce_mean(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

## Product:

In [ ]:
X.prod()

785862000

In [ ]:
tf.math.reduce_prod(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=785862000>

# Dot Product:
* If we have 2 vectors x and y, that have same length. We can calculate Dot product between them. Denoted by:
  * ***x . y***
* We calculate products in an element-wise fashion and then sum reductively across the products to a scalar value. That is, $x \cdot y = \sum_{i=1}^{n} x_i y_i$

* The dot product is ubiquitous in deep learning: It is performed at every artificial neuron in a deep neural network, which may be made up of millions (or orders of magnitude more) of these neurons.

In [ ]:
x = np.array([25, 5, 10])

x

array([25,  5, 10])

In [ ]:
y = np.array([0, 1, 2])

y

array([0, 1, 2])

Product of individual elements, then sum of all.

In [ ]:
25 * 0 + 5 * 1 + 10 * 2

25

In Numpy:

In [ ]:
np.dot(x,y)

25

In tensorFlow:

In [ ]:
x_tf = tf.Variable([25, 5, 10])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  5, 10], dtype=int32)>

In [ ]:
y_tf = tf.Variable([0, 1, 2])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [ ]:
tf.reduce_sum(tf.multiply(x_tf,y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=25>

Segment 2 ends here.