<a href="https://colab.research.google.com/github/Mikkk1/Intro-to-Linear-Algebra-python/blob/main/linearAlg_seg_1_topic_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Vectors and Transpose of a vector:**

### What are vectors?
* One-dimensional array of numbers.
* They are denoted by lower case, italic, bold characters, e.g. ***'x'***
* Arranged in order, so can be accessed by index.

  *   Individual elements of a vector are scalers, so they cannot be represented as bold characters.
* Vectors usually represent a point in space. e.g.,
  * A vector of length 2 represents a location in 2D matrix.
  * A vector of length 3 represents a location in 3D matrix.
  * A vector of length n represents a location in nD matrix.


### Vectors (Rank 1 Tensors) in numpy:

In [2]:
import numpy as np
import tensorflow as tf

In [ ]:
x = np.array([25,5,50]) # We can also specify data type (optional), dtype = np.float16
x

array([25,  5, 50])

In [ ]:
len(x)

3

In [ ]:
x.shape

(3,)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x[0]

25

In [ ]:
x[2]

50

## Vector Transposition:
Changing row into columns and vice versa of a vector.

### In Numpy:

Currently **x** vector has only 1 axis, So, transpose doesn't have any effect on it, Its shape remains same.

In [ ]:
x_t = x.T
x_t

array([25,  5, 50])

In [ ]:
x_t.shape

(3,)

If we use nested matrix style brackets:

In [ ]:
y = np.array([[25,5,50]])
y

array([[25,  5, 50]])

In [ ]:
y.shape

(1, 3)

Now, if we take transpose:

In [ ]:
y_t = y.T
y_t

array([[25],
       [ 5],
       [50]])

In [ ]:
y_t.shape

(3, 1)

### Zero Vectors:


In [ ]:
z = np.zeros(3)
z

array([0., 0., 0.])

## Vectors in TensorFlow:

In [ ]:
x_tf = tf.Variable([25,5,50])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  5, 50], dtype=int32)>

In [ ]:
x_tf = tf.transpose(x_tf)

In [ ]:
x_tf

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25,  5, 50], dtype=int32)>

In [ ]:
y_tf = tf.Variable([[25,5,50]])
y_tf

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[25,  5, 50]], dtype=int32)>

In [ ]:
y_tf = tf.transpose(y_tf)
y_tf

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[25],
       [ 5],
       [50]], dtype=int32)>

# Norms:
* Vectors also represent the magnitude and direction from origin.
* Norms are functions that quantify vector magnitude.

## L1 Norm:
  * L1 Norm **`||x||`** equals to the **`"Sum of Individual scaler elements of the vector"`**
  * It varies at all locations.
  * Used whenever diff b/w zero and non-zero is key.
  * Another common Norm in ML.

In [ ]:
x

array([25,  5, 50])

In [ ]:
np.abs(25) + np.abs(5) + np.abs(50)

80

## L2 Norm:
  * L2 Norm **`||x||`** equals to the **`"Sq root of Sum of square of Individual scaler elements of the vector"`**
  * Represented and Described as:

  * Measures simple Euclidean distance from origin.
  * Most common Norm in ML.

In [ ]:
x

array([25,  5, 50])

In [ ]:
(25**2 + 5**2 + 50**2)**(1/2)

56.124860801609124

#### Using Built in functions:

In [ ]:
np.linalg.norm(x)

56.124860801609124

So, if units in this 3D vector space are meters, then the vector *x* has  length of 56.1m.

## Squared L2 Norm:
  * L2 Norm **`||x||`**^2 equals to the **`"Sum of square of Individual scaler elements of the vector"`**
  * Computationally cheaper to use than L2 norm because:
    * Squared L2 norm equals to (Transpose of **vector x** * **x**)
  * Downside is that it grows slowly near origin, So, cnnot be used if Diff b/w zero and non-zero is important.

In [ ]:
x

array([25,  5, 50])

In [ ]:
(25**2 + 5**2 + 50**2)

3150

In [ ]:
np.dot(x,x)

3150

## Max Norm:
* Equals to the maximum of absolute of all the Individual scaler values of vector.
* Returns the absolute value of the largest magnitude element.

In [ ]:
x

array([25,  5, 50])

In [ ]:
np.max([np.abs(25) , np.abs(5) , np.abs(50)])

50

## Generalized Lp Norm:


# Types of Vectors:

## Unit Vector:
* Vector whose length is equal to 1.
* Technically, x is a unit vector, if it has *unit norm*; i.e.,
  * ||**x**|| = 1

## Basis Vectors:
* Can be scaled to represent any vector in given vector space.
* Typically, use unit vectors along axes of vector space.

## Orthogonal Vectors:
* ***x*** and ***y*** are orthogonal vectors, if *transpose of **x** * **y** = 0*
* These are at 90° angle to each other.(assuming noon-zero norms)
* n-Dimensional space has max n mutually orthogonal vectors.

In [ ]:
i = np.array([1,0])
i

array([1, 0])

In [ ]:
j = np.array([0,1])
j

array([0, 1])

In [ ]:
np.dot(i,j)

0

## Orthonormal Vectors:
* These are orthogonal vectors and have a *Unit Norm*.