<a href="https://colab.research.google.com/github/Mikkk1/Intro-to-Linear-Algebra-python/blob/main/linearAlg_seg_2_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Common Tensor operations:**

## Exercise:

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
Y = np.array([[42, 4, 7, 99], [-99, -3, 17, 22]])
Y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [ ]:
Y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

## Hadamard Product:


In [ ]:
X_tf = tf.Variable([[25, 10],[-2, 1]])
Y_tf = tf.Variable([[-1, 7],[10, 8]])

In [ ]:
X_tf * Y_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-25,  70],
       [-20,   8]], dtype=int32)>

## Dot Product:

In [ ]:
w_tf = tf.Variable([-1, 2, -2])
x_tf = tf.Variable([5, 10, 0])

In [ ]:
tf.reduce_sum(tf.multiply(w_tf,x_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=15>